### ISSUE TITLE
The last few pixels of the distance measurement text are clipped

### ISSUE THREAD

**Issue by TiborGY** [OpenChemistry/avogadrolibs#2007]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.100.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Windows 10
 - Version: 1809

**Describe the bug**
As seen below the last few pixels of the rightmost Å character are clipped when the Measure tool is used on four atoms.

**To Reproduce**
1. Have a 4+ atom molecule
2. Select 4 atoms with the Measure tool
3. Observe the rightmost character in the "Distance:" line

**Expected behavior**
All characters properly displayed

**Screenshots**
![Image](https://github.com/user-attachments/assets/1b3766fe-95f0-43b1-be7b-086ffa2dfe78)

**Comment by ghutchis** [comment]
Can you check this now? I believe a number of these changes were fixed with #2014

**Comment by TiborGY** [comment]
> Can you check this now? I believe a number of these changes were fixed with [#2014](https://github.com/OpenChemistry/avogadrolibs/pull/2014)

Still an issue:

![Image](https://github.com/user-attachments/assets/8dce98fd-ae6c-4e37-9c46-06864f39118c)
