### ISSUE TITLE
Crash. Suddenly.

### ISSUE THREAD

**Issue by Mincci** [OpenChemistry/avogadrolibs#2120]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.99.0
 - Qt: 5.15.13

**Desktop version: (please complete the following information):**
 - OS: Linux Mint, Cinnamon
 - Version: Mint: 22.1, Cinnamon: 6.4.8, Kernel: 6.8.0-64-generic. 
 - Compiler (if you built from source)

**Describe the bug**
I was creating a variant of nitric acid to see if that would be stable. I was drawing a bond between N and H, and as I released the mouse button, the application crashed (no warnings, just closed off). I see errors in the log (I will provide it), which should not be "deleted" imo.  Like "warning: Can't open file /memfd:xorg (deleted) during file-backed mapping note processing", and dconf equivalents. Also, "Program terminated with signal SIGSEGV, Segmentation fault." may bring you some clarity (?) Sorry if I did something wrong, as I have not sent a report like this before. 

**To Reproduce**
Seems to happen "suddenly" without following the same steps. So I don't know. Happened twice now.

**Expected behavior**
I expected the Hydrogen atom to be bonded to the nitrogen. 

**Screenshots**
It was a sudden crash, so I have no screenshots.

**Additional context**
Add any other context about the p

[crash.tar.gz](https://github.com/user-attachments/files/21482277/crash.tar.gz)

**Comment by matterhorn103** [comment]
This sounds like something that may have been fixed by various recent changes to the automatic bond adjustment logic.

I assume you got 1.99 from the Linux Mint repos?

Would you mind trying either the [beta Flatpak](https://two.avogadro.cc/install/flatpak.html#beta) or the [nightly AppImage](https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_linux/master/Avogadro2-x86_64.AppImage.zip) and seeing if you encounter the same issue?

**Comment by Mincci** [comment]
Yes, from Mint repos. I had some Python 3 anomaly a while back. I still don't understand why or how it was possible (some strange chain reaction). I was using pipx as always, to avoid affecting stuff from outside the Python environment. I was following the installation guide to the word for an app, which required every part of it to be built and configured manually (a real headache), but it worked in the end. 

Soon, after that, I noticed that "2to3" seemed to be installed, but not "available", and ran apt check (huge wall of errors, and just a few days ago there were no errors in deps or anything), and such. Soon, I noticed the strange part - my sources.list was modified, and I had lost all the custom repos, and others too were "wrong". I thought "I just overwrite it from my timeshift...", but to my confusion, the sources.list in timeshift was also modified, and just a while ago. That is not normal to my understanding. So, because "apt check" gave heavy errors regarding Python, and even Grub and such critical parts were "there, but not there", and needed to be configured again to find other OSes. I created a new and proper sources.list from scratch, and then had to reinstall and recreate the config for hundreds of packages, and finally, there were no more errors, and I dared to reboot. And it did not produce any errors either. 

About two weeks after that, I installed Avogadro - without problems. And it seems everything, Python included, is now working properly. Probably this has nothing to do with these crashes, as nothing else is crashing. But I thought to mention it because nothing like it has ever happened on any distro I've used. 

> Would you mind trying either the [beta Flatpak](https://two.avogadro.cc/install/flatpak.html#beta) or the [nightly AppImage](https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_linux/master/Avogadro2-x86_64.AppImage.zip) and seeing if you encounter the same issue?

Sure. I seem to have a kernel upgrade waiting, so I will do that, and if the problem happens again, I will try those and report. Also, if the problem does not happen, I'll say something. (For now, the app has been running for hours on the background without any issues, so at least we can narrow it down to be a result of some action inside the app, and not random event while running it idle.

**Comment by matterhorn103** [comment]
My gut feeling is that it doesn't have anything to do with Python, but good to know that you've been having those troubles on your system in case they're a factor.

Did you get round to trying the AppImage and/or Flatpak?

**Comment by Mincci** [comment]
I have not tried those, because there has been no single crash since. I tried pulling different bonds around different compounds, and using random "objects", settings, and tools to affect the bonds in different ways. I don't know what may have been the cause of those two crashes. I tried to replicate the events that were leading to the crash, but not this time. It happened last time when the bond was supposed to snap in place (on mouse-up). I have no idea what caused it, but if it does crash again, I will say. If there is something specific for me to try inside the app, I am happy to help. Maybe my modification to HNO3 broke the laws of physics and/or /0 was imminent. (Sorry, if this is not the place for "jokes".)

**Comment by ghutchis** [comment]
Jokes are fine. 👍  We've fixed a few issues since 1.99, so my hope is that it won't happen again in 1.100 or 1.101 once that's released.

Certainly, if you get a crash and can paste something from the crash log, that's always very helpful. (And hopefully even unusual modifications to HNO3 that break the laws of physics don't crash the app.)

**Comment by matterhorn103** [comment]
Glad it's been working fine since! I'll close the issue for now, since we don't have anything actionable. If it happens again then post some details here and we can reopen it. 🙂
