### ISSUE TITLE
Opening molecular properties dialog results in crash

### ISSUE THREAD

**Issue by Kcorbyerd** [OpenChemistry/avogadrolibs#2390]
**Avogadro version:**
 - Avogadrolibs: 1.102.1 (nightly downloaded on 11/7/2025)
 - Qt: 6.10.0

**Desktop version: (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 10.0.26100

**Describe the bug**
Trying to use `Analyze>Properties>Molecular...` results in a crash.

**To Reproduce**
1. Open an `xyz` or `cjson` file or just draw a molecule (empty documents don't cause the crash)
2. Go to `Analyze>Properties>Molecular...`
3. Observe.

**Expected behavior**
Display molecular properties.

Here's the two files I used, as well as the log from Avogadro 2.
[formic_acid_and_log.zip](https://github.com/user-attachments/files/23422913/formic_acid_and_log.zip)

The error right before the crash is
```
Warning: "C:/Program Files/Avogadro2/bin/obabel.exe"  stderr:
 "1 molecule converted\r\n" (:0, )
```

**Comment by ghutchis** [comment]
I cannot reproduce this. I would guess there's a problem accessing the name from PubChem? Does it matter whether there's a network connection / WiFi?

**Comment by ghutchis** [comment]
I'm pretty sure this is fixed by #2509

**Comment by ghutchis** [comment]
@brockdyer03 - can you give a continuous build a try and let me know if it solves this one? Thanks

**Comment by brockdyer03** [comment]
Just downloaded the nightly, still crashes. I know 1.102.1 release worked, but the current nightlies do not.

**Comment by ghutchis** [comment]
Huh. Let me see if I can figure out what changed between the release. It's hard because I don't have easy access to a Windows machine to run `git bisect` and test

**Comment by ghutchis** [comment]
I can't see any obvious changes between Nov. 7th and the 1.102.1 release, except for some build-related things.

If you use "download by name" or "download plugins" (which also use network access) do those crash too?

Also, you've been able to compile on your own Windows box. Does that crash?

**Comment by ghutchis** [comment]
Bump? Can you check with the latest continuous?

**Comment by ghutchis** [comment]
Okay, you just confirmed it doesn't crash. Closing this.
